import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class PaysVilleService {

  private pays:{[villes:string]:string[]}={
  "Afghanistan": ["Kaboul", "Herat","Kandahar", "Mazar-i-Sharif", "Jalalabad", "Kunduz"],
  "Afrique du Sud": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein"],
  "Åland, Îles": ["Mariehamn", "Jomala", "Finström", "Lemland", "Saltvik", "Hammarland"],
  "Albanie": ["Tirana", "Durrës", "Vlorë", "Shkodër", "Fier", "Elbasan"],
  "Algérie": ["Alger", "Oran", "Constantine", "Annaba", "Blida", "Batna"],
  "Allemagne": ["Berlin", "Munich", "Francfort", "Hambourg", "Cologne", "Stuttgart"],
  "Allemagne de l'EST": ["Berlin-Est", "Leipzig", "Dresde", "Magdebourg", "Rostock", "Erfurt"],
  "Andorre": ["Andorre-la-Vieille", "Escaldes-Engordany", "Encamp", "La Massana", "Sant Julià de Lòria", "Ordino"],
  "Angola": ["Luanda", "Benguela", "Huambo", "Lubango", "Lobito", "Namibe"],
  "Anguilla": ["The Valley", "Blowing Point", "East End", "Sandy Ground", "Island Harbour", "George Hill"],
  "Antarctique": ["McMurdo Station", "Scott Base", "Palmer Station", "Rothera Research Station", "Mawson Station", "Vostok Station"],
  "Antigua et Barbuda": ["Saint John's", "All Saints", "Liberta", "Parham", "Falmouth", "Bolands"],
  "Antilles néerlandaises": ["Willemstad", "Kralendijk", "Oranjestad", "Philipsburg", "Rincon", "Dorp Sint Michiel"],
  "Arabie Saoudite": ["Riyad", "Djeddah", "La Mecque", "Médine", "Dammam", "Khobar"],
  "Argentine": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "Mar del Plata"],
  "Arménie": ["Erevan", "Gyumri", "Vanadzor", "Hrazdan", "Abovyan", "Kapan"],
  "Aruba": ["Oranjestad", "San Nicolas", "Santa Cruz", "Paradera", "Savaneta", "Noord"],
  "Australie": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra"],
  "Autriche": ["Vienne", "Graz", "Linz", "Salzbourg", "Innsbruck", "Klagenfurt"],
  "Azerbaïdjan": ["Bakou", "Ganja", "Sumqayit", "Mingachevir", "Lankaran", "Shirvan"],
  "Bahamas": ["Nassau", "Freeport", "West End", "Cooper's Town", "Marsh Harbour", "High Rock"],
  "Bahrein": ["Manama", "Riffa", "Muharraq", "Hamala", "Isa Town", "Jidhafs"],
  "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Barisal"],
  "Barbade": ["Bridgetown", "Speightstown", "Oistins", "Bathsheba", "Holetown", "Crane"],
  "Bélarus": ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Hrodna", "Brest"],
  "Belgique": ["Bruxelles", "Anvers", "Gand", "Charleroi", "Liège", "Bruges"],
  "Bélize": ["Belmopan", "Belize City", "San Ignacio", "Orange Walk Town", "Dangriga", "Corozal Town"],
  "Bénin": ["Cotonou", "Porto-Novo", "Parakou", "Djougou", "Bohicon", "Abomey"],
  "Bermudes": ["Hamilton", "St. George's", "Somerset Village", "Flatts Village", "Tucker's Town", "Mount Pleasant"],
  "Bhoutan": ["Thimphou", "Phuentsholing", "Paro", "Punakha", "Jakar", "Trashigang"],
  "Bolivie (État plurinational de)": ["La Paz", "Santa Cruz de la Sierra", "Cochabamba", "Sucre", "Oruro", "Potosí"],
  "Bonaire, Saint-Eustache et Saba": ["Kralendijk", "Oranjestad", "The Bottom", "Rincon", "Zuid", "Hato"],
  "Bosnie-Herzégovine": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Bijeljina"],
  "Botswana": ["Gaborone", "Francistown", "Molepolole", "Selebi-Phikwe", "Maun", "Serowe"],
  "Bouvet, Ile": ["Bouvet Island"],
  "Brésil": ["Brasilia", "São Paulo", "Rio de Janeiro", "Salvador", "Fortaleza", "Belo Horizonte"],
  "Brunéi Darussalam": ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Bangar", "Muara"],
  "Bulgarie": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora"],
  "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Banfora", "Ouahigouya", "Pouytenga"],
  "Burundi": ["Bujumbura", "Gitega", "Ngozi", "Ruyigi", "Muramvya", "Kayanza"],
  "Cabo Verde": ["Praia", "Mindelo", "Santa Maria", "Espargos", "Assomada", "Tarrafal"],
  "Caïmans, Iles": ["George Town", "West Bay", "Bodden Town", "East End", "North Side", "Cayman Brac"],
  "Cambodge": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Kampong Cham", "Takeo"],
  "Cameroun": ["Yaoundé", "Douala", "Garoua", "Bamenda", "Maroua", "Bafoussam"],
  "Canada": ["Toronto", "Montréal", "Vancouver", "Calgary", "Edmonton", "Ottawa"],
  "Chili": ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco"],
  "Chine": ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Wuhan"],
  "Christmas, île": ["Flying Fish Cove"],
  "Chypre": ["Nicosie", "Limassol", "Larnaca", "Famagouste", "Paphos", "Kyrenia"],
  "Cocos/Keeling (Îles)": ["West Island", "Home Island"],
  "Colombie": ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Bucaramanga"],
  "Comores": ["Moroni", "Mutsamudu", "Fomboni", "Domoni", "Ouani", "Mirontsi"],
  "Congo": ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Owando", "Ouésso"],
  "Congo, République démocratique du": ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kisangani", "Kananga", "Goma"],
  "Cook, Iles": ["Avarua", "Arutanga", "Omoka", "Tautu", "Matavera", "Titikaveka"],
  "Corée, République de": ["Séoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju"],
  "Corée, République populaire démocratique de": ["Pyongyang", "Hamhung", "Nampo", "Sunchon", "Wonsan", "Kaesong"],
  "Costa Rica": ["San José", "Alajuela", "Cartago", "Heredia", "Puntarenas", "Liberia"],
  "Côte d'Ivoire": ["Abidjan", "Bouaké", "Daloa", "San Pedro", "Yamoussoukro", "Korhogo"],
  "Croatie": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Pula"],
  "Cuba": ["La Havane", "Santiago de Cuba", "Camagüey", "Holguín", "Guantánamo", "Santa Clara"],
  "Curaçao": ["Willemstad", "Sint Michiel", "Dorp Soto", "Nieuwpoort", "Barber", "Dorp Nikiboko"],
  "Danemark": ["Copenhague", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers"],
  "Djibouti": ["Djibouti", "Ali Sabieh", "Tadjourah", "Obock", "Dikhil", "Arta"],
  "Dominicaine, République": ["Saint-Domingue", "Santiago", "San Pedro de Macorís", "La Romana", "San Francisco de Macorís", "Puerto Plata"],
  "Dominique": ["Roseau", "Portsmouth", "Marigot", "Berekua", "Mahaut", "Wesley"],
  "Egypte": ["Le Caire", "Alexandrie", "Gizeh", "Shubra El-Kheima", "Port-Saïd", "Suez"],
  "El Salvador": ["San Salvador", "Santa Ana", "San Miguel", "Soyapango", "Santa Tecla", "Mejicanos"],
  "Emirats arabes unis": ["Abou Dabi", "Dubaï", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah"],
  "Equateur": ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Machala", "Durán"],
  "Erythrée": ["Asmara", "Keren", "Massawa", "Assab", "Mendefera", "Barentu"],
  "Espagne": ["Madrid", "Barcelone", "Valence", "Séville", "Saragosse", "Malaga"],
  "Estonie": ["Tallinn", "Tartu", "Narva", "Pärnu", "Viljandi", "Rakvere"],
  "Etats-Unis d'Amérique": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia"],
  "Ethiopie": ["Addis-Abeba", "Gondar", "Mekelle", "Adama", "Dire Dawa", "Hawassa"],
  "Falkland/Malouines (Îles)": ["Stanley", "Mount Pleasant"],
  "Féroé, îles": ["Tórshavn", "Klaksvík", "Hoyvík", "Argir", "Fuglafjørður", "Vestmanna"],
  "Fidji": ["Suva", "Nadi", "Lautoka", "Labasa", "Ba", "Levuka"],
  "Finlande": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku"],
  "France": ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Nantes"],
  "Gabon": ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda", "Makokou"],
  "Gambie": ["Banjul", "Serrekunda", "Brikama", "Bakau", "Farafenni", "Lamin"],
  "Géorgie": ["Tbilissi", "Batoumi", "Koutaïssi", "Roustavi", "Soukhoumi", "Zugdidi"],
  "Géorgie du sud et les îles Sandwich du sud": ["King Edward Point", "Grytviken"],
  "Ghana": ["Accra", "Kumasi", "Sekondi-Takoradi", "Tamale", "Ashaiman", "Cape Coast"],
  "Gibraltar": ["Gibraltar"],
  "Grèce": ["Athènes", "Thessalonique", "Patras", "Héraklion", "Larissa", "Volos"],
  "Grenade": ["Saint George's", "Gouyave", "Grenville", "Victoria", "Sauteurs", "Hillsborough"],
  "Groenland": ["Nuuk", "Sisimiut", "Ilulissat", "Qaqortoq", "Aasiaat", "Maniitsoq"],
  "Guadeloupe": ["Pointe-à-Pitre", "Les Abymes", "Le Gosier", "Baie-Mahault", "Petit-Bourg", "Sainte-Anne"],
  "Guam": ["Hagåtña", "Dededo", "Tamuning", "Yigo", "Mangilao", "Barrigada"],
  "Guatemala": ["Guatemala", "Mixco", "Villa Nueva", "Quetzaltenango", "Escuintla", "Santa Catarina Pinula"],
  "Guernesey": ["Saint Peter Port", "Saint Sampson", "Vale", "Castel", "Saint Martin", "Forest"],
  "Guinée": ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé", "Mamou"],
  "Guinée-Bissau": ["Bissau", "Bafatá", "Gabu", "Bissorã", "Bolama", "Cacheu"],
  "Guinée équatoriale": ["Malabo", "Bata", "Ebebiyin", "Aconibe", "Mongomo", "Evinayong"],
  "Guyana": ["Georgetown", "Linden", "New Amsterdam", "Anna Regina", "Bartica", "Skeldon"],
  "Guyane française": ["Cayenne", "Saint-Laurent-du-Maroni", "Kourou", "Matoury", "Macouria", "Maripasoula"],
  "Haïti": ["Port-au-Prince", "Cap-Haïtien", "Gonaïves", "Les Cayes", "Port-de-Paix", "Jacmel"],
  "Heard, Ile et MacDonald, îles": ["Heard Island"],
  "Honduras": ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba", "El Progreso", "Comayagua"],
  "Hong Kong": ["Hong Kong"],
  "Hongrie": ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs", "Győr"],
  "Île de Man": ["Douglas", "Onchan", "Ramsey", "Peel", "Port Erin", "Castletown"],
  "Îles mineures éloignées des Etats-Unis": ["Midway Atoll", "Wake Island"],
  "Îles vierges britanniques": ["Road Town", "Spanish Town"],
  "Îles vierges des Etats-Unis": ["Charlotte Amalie", "Christiansted", "Frederiksted"],
  "Inde": ["Delhi", "Mumbai", "Bangalore", "Chennai", "Kolkata", "Hyderabad"],
  "Indien (Territoire britannique de l'océan)": ["Diego Garcia"],
  "Indonésie": ["Jakarta", "Surabaya", "Bandung", "Medan", "Bekasi", "Palembang"],
  "Iran, République islamique d'": ["Téhéran", "Mashhad", "Ispahan", "Karaj", "Shiraz", "Tabriz"],
  "Iraq": ["Bagdad", "Bassorah", "Mossoul", "Erbil", "Karbala", "Nadjaf"],
  "Irlande": ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda"],
  "Islande": ["Reykjavik", "Kopavogur", "Hafnarfjordur", "Akureyri", "Reykjanesbaer", "Gardabaer"],
  "Israël": ["Jérusalem", "Tel Aviv-Jaffa", "Haïfa", "Rishon LeZion", "Petah Tikva", "Ashdod"],
  "Italie": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Gênes"],
  "Jamaïque": ["Kingston", "Portmore", "Montego Bay", "Spanish Town", "Mandeville", "Ocho Rios"],
  "Japon": ["Tokyo", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe"],
  "Jersey": ["Saint Helier", "Saint Saviour", "Saint Brelade", "Saint Clement", "Grouville", "Trinity"],
  "Jordanie": ["Amman", "Irbid", "Zarqa", "Russeifa", "Wadi as-Ser", "Aqaba"],
  "Kazakhstan": ["Almaty", "Astana", "Shymkent", "Karaganda", "Aktobe", "Taraz"],
  "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika"],
  "Kirghizistan": ["Bichkek", "Och", "Djalalabad", "Karakol", "Tokmok", "Naryn"],
  "Kiribati": ["Tarawa", "Betio", "Bikenibeu", "Bairiki", "Eita", "Temwaiku"],
  "Koweït": ["Koweït", "Al Ahmadi", "Hawalli", "Mubarak Al-Kabeer", "Farwaniya", "Jahra"],
  "Lao, République démocratique populaire": ["Vientiane", "Pakse", "Savannakhet", "Luang Prabang", "Thakhek", "Muang Xay"],
  "Lesotho": ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse", "Mohale's Hoek", "Qacha's Nek"],
  "Lettonie": ["Riga", "Daugavpils", "Liepaja", "Jelgava", "Jurmala", "Ventspils"],
  "Liban": ["Beyrouth", "Tripoli", "Sidon", "Zahlé", "Jounieh", "Byblos"],
  "Libéria": ["Monrovia", "Gbarnga", "Kakata", "Bensonville", "Harper", "Voinjama"],
  "Libye": ["Tripoli", "Benghazi", "Misrata", "Bayda", "Zawiya", "Zliten"],
  "Liechtenstein": ["Vaduz", "Schaan", "Balzers", "Triesen", "Eschen", "Mauren"],
  "Lituanie": ["Vilnius", "Kaunas", "Klaipeda", "Šiauliai", "Panevėžys", "Alytus"],
  "Luxembourg": ["Luxembourg", "Esch-sur-Alzette", "Differdange", "Dudelange", "Ettelbruck", "Diekirch"],
  "Macao": ["Macao", "Taipa", "Coloane"],
  "Macédoine, l'ex-République yougoslave de": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Veles"],
  "Madagascar": ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga", "Toliara"],
  "Malaisie": ["Kuala Lumpur", "George Town", "Ipoh", "Johor Bahru", "Malacca", "Kota Kinabalu"],
  "Malawi": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu", "Mangochi"],
  "Maldives": ["Malé", "Addu City", "Fuvahmulah", "Thinadhoo", "Hithadhoo", "Kulhudhuffushi"],
  "Mali": ["Bamako", "Sikasso", "Koutiala", "Ségou", "Mopti", "Gao"],
  "Malte": ["Valletta", "Birkirkara", "Mosta", "Qormi", "Sliema", "San Pawl il-Baħar"],
  "Mariannes du nord, Iles": ["Saipan", "Tinian", "Rota"],
  "Maroc": ["Casablanca", "Rabat", "Fès", "Marrakech", "Tanger", "Agadir"],
  "Marshall, Iles": ["Majuro", "Ebeye"],
  "Martinique": ["Fort-de-France", "Le Lamentin", "Le Robert", "Sainte-Marie", "Le François", "Ducos"],
  "Maurice": ["Port-Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes", "Goodlands"],
  "Mauritanie": ["Nouakchott", "Nouadhibou", "Kaédi", "Zouérat", "Néma", "Rosso"],
  "Mayotte": ["Mamoudzou", "Koungou", "Dzaoudzi", "Pamandzi", "Dembeni", "Sada"],
  "Mexique": ["Mexico", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León"],
  "Micronésie, Etats Fédérés de": ["Palikir", "Kolonia", "Weno"],
  "Moldova, République de": ["Chișinău", "Tiraspol", "Bălți", "Bender", "Rîbnița", "Cahul"],
  "Monaco": ["Monaco"],
  "Mongolie": ["Oulan-Bator", "Erdenet", "Darkhan", "Choibalsan", "Mörön", "Nalaikh"],
  "Monténégro": ["Podgorica", "Nikšić", "Herceg Novi", "Pljevlja", "Bijelo Polje", "Bar"],
  "Montserrat": ["Plymouth", "Brades"],
  "Mozambique": ["Maputo", "Matola", "Beira", "Nampula", "Chimoio", "Nacala"],
  "Myanmar": ["Naypyidaw", "Yangon", "Mandalay", "Mawlamyine", "Bago", "Pathein"],
  "Namibie": ["Windhoek", "Rundu", "Walvis Bay", "Swakopmund", "Oshakati", "Rehoboth"],
  "Nauru": ["Yaren", "Aiwo"],
  "Népal": ["Katmandou", "Pokhara", "Lalitpur", "Biratnagar", "Birgunj", "Dharan"],
  "Nicaragua": ["Managua", "León", "Masaya", "Chinandega", "Matagalpa", "Estelí"],
  "Niger": ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Dosso"],
  "Nigéria": ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt", "Benin City"],
  "Niue": ["Alofi"],
  "Norfolk, Ile": ["Kingston"],
  "Norvège": ["Oslo", "Bergen", "Stavanger", "Trondheim", "Drammen", "Fredrikstad"],
  "Nouvelle-Calédonie": ["Nouméa", "Mont-Dore", "Dumbéa", "Païta", "Lifou", "Wé"],
  "Nouvelle-Zélande": ["Wellington", "Auckland", "Christchurch", "Hamilton", "Tauranga", "Dunedin"],
  "Oman": ["Mascate", "Sohar", "Salalah", "Nizwa", "Sur", "Bawshar"],
  "Ouganda": ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja", "Bwizibwera"],
  "Ouzbékistan": ["Tachkent", "Samarcande", "Namangan", "Andijan", "Boukhara", "Noukous"],
  "Pakistan": ["Islamabad", "Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Multan"],
  "Palaos": ["Ngerulmud", "Koror"],
  "Palestine, Etat de": ["Ramallah", "Gaza", "Hébron", "Naplouse", "Rafah", "Jénine"],
  "Panama": ["Panama", "San Miguelito", "Tocumen", "David", "Colón", "La Chorrera"],
  "Papouasie-Nouvelle-Guinée": ["Port Moresby", "Lae", "Arawa", "Mount Hagen", "Madang", "Wewak"],
  "Paraguay": ["Asuncion", "Ciudad del Este", "San Lorenzo", "Luque", "Capiatá", "Lambaré"],
  "Pays-Bas": ["Amsterdam", "Rotterdam", "La Haye", "Utrecht", "Eindhoven", "Tilburg"],
  "Pays inconnu": ["Inconnu"],
  "Pays multiples": ["Multiples"],
  "Pérou": ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Iquitos", "Piura"],
  "Philippines": ["Manille", "Quezon City", "Caloocan", "Davao City", "Cebu City", "Zamboanga City"],
  "Pitcairn": ["Adamstown"],
  "Pologne": ["Varsovie", "Cracovie", "Łódź", "Wrocław", "Poznań", "Gdańsk"],
  "Polynésie française": ["Papeete", "Faaa", "Punaauia", "Mahina", "Papara", "Arue"],
  "Porto Rico": ["San Juan", "Bayamón", "Carolina", "Ponce", "Caguas", "Guaynabo"],
  "Portugal": ["Lisbonne", "Porto", "Amadora", "Braga", "Coimbra", "Funchal"],
  "Qatar": ["Doha", "Al Rayyan", "Al Wakrah", "Umm Salal Muhammad", "Al Khor", "Dukhan"],
  "République arabe syrienne": ["Damas", "Alep", "Homs", "Lattaquié", "Hama", "Deir ez-Zor"],
  "République centrafricaine": ["Bangui", "Bimbo", "Berbérati", "Carnot", "Bambari", "Bouar"],
  "Réunion": ["Saint-Denis", "Saint-Paul", "Saint-Pierre", "Le Tampon", "Saint-André", "Le Port"],
  "Roumanie": ["Bucarest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova"],
  "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord": ["Londres", "Birmingham", "Glasgow", "Liverpool", "Manchester", "Edimbourg"],
  "Russie, Fédération de": ["Moscou", "Saint-Pétersbourg", "Novossibirsk", "Ekaterinbourg", "Nijni Novgorod", "Samara"],
  "Rwanda": ["Kigali", "Butare", "Gisenyi", "Byumba", "Ruhengeri", "Cyangugu"],
  "Sahara occidental": ["El-Aaiún", "Dakhla", "Smara", "Boujdour", "Laayoune Plage"],
  "Saint-Barthélemy": ["Gustavia"],
  "Saint-Kitts-et-Nevis": ["Basseterre", "Charlestown"],
  "Saint-Marin": ["Saint-Marin", "Serravalle"],
  "Saint-Martin (partie française)": ["Marigot", "Grand Case", "Cul de Sac"],
  "Saint-Martin (partie néerlandaise)": ["Philipsburg", "Lower Prince’s Quarter", "Cole Bay"],
  "Saint-Pierre-et-Miquelon": ["Saint-Pierre", "Miquelon"],
  "Saint-Siège": ["Vatican"],
  "Saint-Vincent-et-les-Grenadines": ["Kingstown", "Georgetown", "Byera Village"],
  "Sainte-Hélène, Ascension et Tristan da Cunha": ["Jamestown", "Georgetown", "Edinburgh of the Seven Seas"],
  "Sainte-Lucie": ["Castries", "Vieux Fort", "Gros Islet", "Micoud", "Dennery"],
  "Salomon, Iles": ["Honiara", "Gizo", "Auki"],
  "Samoa": ["Apia", "Vaitele", "Faleula", "Siusega", "Malie"],
  "Samoa américaines": ["Pago Pago", "Tafuna", "Nu’uuli", "Fagatogo"],
  "Sao Tomé-et-Principe": ["São Tomé", "Trindade", "Santa Cruz"],
  "Sénégal": ["Dakar", "Touba", "Thiès", "Saint-Louis", "Kaolack", "Ziguinchor"],
  "Serbie": ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin"],
  "Seychelles": ["Victoria", "Anse Boileau", "Bel Ombre"],
  "Sierra Leone": ["Freetown", "Bo", "Kenema", "Makeni", "Koidu", "Lunsar"],
  "Singapour": ["Singapour"],
  "Slovaquie": ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra", "Banská Bystrica"],
  "Slovénie": ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper"],
  "Somalie": ["Mogadiscio", "Hargeisa", "Bosaso", "Kismayo", "Baidoa", "Burao"],
  "Soudan": ["Khartoum", "Omdourman", "Port-Soudan", "Nyala", "El Obeid", "El-Gadarif"],
  "Soudan du Sud": ["Juba", "Malakal", "Wau", "Bor", "Yambio", "Rumbek"],
  "Sri Lanka": ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo", "Anuradhapura"],
  "Suède": ["Stockholm", "Göteborg", "Malmö", "Uppsala", "Västerås", "Örebro"],
  "Suisse": ["Zurich", "Genève", "Bâle", "Lausanne", "Berne", "Winterthour"],
  "Suriname": ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo", "Mariënburg"],
  "Svalbard et île Jan Mayen": ["Longyearbyen"],
  "Swaziland": ["Mbabane", "Manzini", "Big Bend"],
  "Tadjikistan": ["Douchanbé", "Khujand", "Kulob", "Qurghonteppa", "Istaravshan", "Konibodom"],
  "Taïwan, Province de Chine": ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Hsinchu", "Keelung"],
  "Tanzanie, République unie de": ["Dodoma", "Dar es Salaam", "Mwanza", "Arusha", "Mbeya", "Morogoro"],
  "Tchad": ["N'Djamena", "Moundou", "Sarh", "Abeche", "Kelo", "Koumra"],
  "Tchécoslovaquie": ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc"],
  "Tchèque, République": ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc"],
  "Terres australes françaises": ["Port-aux-Français"],
  "Thaïlande": ["Bangkok", "Nonthaburi", "Nakhon Ratchasima", "Chiang Mai", "Hat Yai", "Pak Kret"],
  "Timor-Leste": ["Dili", "Baucau", "Maliana", "Suai", "Lospalos", "Same"],
  "Togo": ["Lomé", "Sokodé", "Kara", "Kpalimé", "Atakpamé", "Bassar"],
  "Tokelau": ["Fakaofo", "Nukunonu", "Atafu"],
  "Tonga": ["Nuku'alofa", "Neiafu", "Haveluloto", "Vaini", "Pangai"],
  "Trinité-et-Tobago": ["Port-d'Espagne", "San Fernando", "Chaguanas", "Arima", "Scarborough", "Point Fortin"],
  "Tunisie": ["Tunis", "Sfax", "Sousse", "Ettadhamen", "Kairouan", "Bizerte"],
  "Turkménistan": ["Achgabat", "Turkmenabat", "Dashoguz", "Mary", "Balkanabat", "Bayramaly"],
  "Turks-et-Caïcos (Îles)": ["Cockburn Town", "Grand Turk", "Providenciales"],
  "Turquie": ["Ankara", "Istanbul", "Izmir", "Bursa", "Adana", "Gaziantep"],
  "Tuvalu": ["Funafuti"],
  "Ukraine": ["Kiev", "Kharkiv", "Odessa", "Dnipro", "Donetsk", "Zaporizhia"],
  "URSS": ["Moscou", "Saint-Pétersbourg", "Kiev", "Minsk", "Alma-Ata", "Tachkent"],
  "Uruguay": ["Montevideo", "Salto", "Ciudad de la Costa", "Paysandú", "Las Piedras", "Rivera"],
  "Vanuatu": ["Port-Vila", "Luganville"],
  "Vatican : voir Saint-Siège": ["Vatican"],
  "Venezuela (République bolivarienne du)": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Ciudad Guayana", "Maturín"],
  "Viet Nam": ["Hanoï", "Ho Chi Minh Ville", "Haiphong", "Da Nang", "Bien Hoa", "Can Tho"],
  "Wallis et Futuna": ["Mata-Utu"],
  "Yémen": ["Sanaa", "Aden", "Ta'izz", "Al Hudaydah", "Ibb", "Dhamar"],
  "Yougoslavie": ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin"],
  "Zaïre": ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani", "Bukavu"],
  "Zambie": ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola", "Mufulira"],
  "Zimbabwe": ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Epworth"]
};
constructor() { }
getpays():string[] {
  return Object.keys(this.pays);

}
getvilles(pays:string):string[]{
  return this.pays[pays];
}
 }













  






 